# frozen_string_literal: true

require "rack/files"

module Framework
  # Serves the gem release archive and docs chrome from Engine.root so hosts never
  # need `framework:fetch`. Inserted ahead of ActionDispatch::Static so the gem
  # wins over any stale host copies under public/.
  class Static
    PUBLIC_PREFIXES = %w[
      /css/
      /js/
      /fonts/
      /images/
      /framework/colors/
      /framework/releases/
      /framework/example_fixtures/
      /framework/docs/
      /framework/examples/
    ].freeze

    # The LLM docs index, advertised at the host root. Generated by
    # `rake framework:generate_markdown`, like the .md twins under /framework/docs/.
    ROOT_PUBLIC_FILES = %w[llms.txt llms-full.txt].freeze

    FRAMEWORK_ZIP = %r{\A/framework/trmnl-framework--[^/]+\.zip\z}.freeze

    # Precompressed siblings a release publishes, best encoding first. Serving them needs no
    # compressor here: the release wrote the bytes, this only picks the file and names the
    # encoding, so the gem stays free of a brotli dependency at runtime.
    PRECOMPRESSED_ENCODINGS = [["br", ".br"], ["gzip", ".gz"]].freeze

    # A path carrying a semver names one published release, and a published release is never
    # re-cut (RELEASE.md), so those bytes can be held forever. Everything else here is a
    # rolling name: css/latest, the fonts, the images, and the docs chrome all change under
    # the same URL, so they revalidate on the short window instead.
    IMMUTABLE_PATH = %r{\A/(?:css|js)/\d+\.\d+\.\d+/|\A/framework/colors/\d+\.\d+\.\d+/|--\d+\.\d+\.\d+\.zip\z}.freeze
    IMMUTABLE_CACHE_CONTROL = "public, max-age=#{365 * 24 * 60 * 60}, immutable".freeze
    DEFAULT_CACHE_CONTROL = "public, max-age=#{60 * 60}".freeze
    # /framework-dev/ is the live build on a host in development mode, rebuilt under a URL
    # that never moves, so it revalidates on every request rather than after an hour.
    DEV_CACHE_CONTROL = "no-cache"

    DOCS_FILES = {
      "screen_class_sync.js" => ->(root) { root.join("app/javascript/framework_docs/lib/screen_class_sync.js") },
      "framework_iframe_bridge.js" => ->(root) { root.join("app/javascript/framework_iframe_bridge.js") },
      "plugin_legacy.js" => ->(root) { root.join("app/javascript/plugin_legacy.js") },
      "plugins.js" => ->(root) { root.join("app/javascript/plugin-render/plugins.js") },
      "prism_trmnl.css" => ->(root) { root.join("app/assets/static/prism_trmnl.css") },
      # Vendored the same way core vendors them, under the same filenames, so the docs
      # linked whichever copy the host's load path answered with first. Prism is the
      # visible one: a host on a different build highlights these samples with a
      # tokenizer the theme next to it was never matched against.
      "prism-1.29.0.min.js" => ->(root) { root.join("vendor/javascript/prism-1.29.0.min.js") },
      "jquery-3.6.0.min.js" => ->(root) { root.join("vendor/javascript/jquery-3.6.0.min.js") },
      # MapLibre GL JS (BSD), the library behind TRMNLMaps. Vendored and served off the
      # engine tree so the map docs and a plugin on a host that mounts the engine load it
      # from the same origin as the runtime; docs/MAPS_GO_LIVE.md is where that URL would
      # move to a CDN. 5.24.0 is the last UMD build (6.x ships ESM only), and a plugin
      # loads it with a classic script tag and reads window.maplibregl.
      "maplibre-gl-5.24.0.js" => ->(root) { root.join("vendor/javascript/maplibre-gl-5.24.0.js") },
      "maplibre-gl-5.24.0.css" => ->(root) { root.join("vendor/javascript/maplibre-gl-5.24.0.css") },
      # Framework.server_builds is the only live-build candidate any of these chains has.
      # dartsass and Tailwind write to the host's Rails.root, which in this repo is server/,
      # so the engine root's own app/assets/builds/ is never a build target. It was listed
      # here as a second candidate, left from the pre-engine layout where Rails.root was the
      # repo root, and after that move it could only ever resolve to output compiled before
      # it: a checkout that still had one served a months-old bundle in place of the build
      # it had just compiled.
      "plugins.css" => lambda { |root|
        [
          Framework.server_builds.join("plugins.css"),
          root.join("public/css/latest/plugins.css")
        ].find(&:exist?)
      },
      # The v1.2 bundle, same shape as the docs chrome below: the live build wins where
      # one exists, and the packaged snapshot answers everywhere else. It is not a
      # release asset (no version ever published one), so there is nothing to look for
      # under public/css/latest; that candidate resolved nowhere and left this whole
      # chain a dead end in an installed gem.
      "plugins_legacy.css" => lambda { |root|
        [
          Framework.server_builds.join("plugins_legacy.css"),
          root.join("app/assets/static/legacy_bundle.css")
        ].find(&:exist?)
      },
      # Docs chrome. The live build wins where one exists (bin/dev rebuilds it on
      # every view edit); the packaged snapshot is what a host that never runs
      # Tailwind gets, so /framework renders styled out of the box.
      "tailwind.css" => lambda { |root|
        [
          Framework.server_builds.join("tailwind.css"),
          root.join("app/assets/static/docs_chrome.css")
        ].find(&:exist?)
      }
    }.freeze

    # A host in development mode symlinks public/framework-dev at the developer's own
    # framework checkout (rake framework:development:enable). Prefer that when it is
    # there. The engine tree is whatever the pinned release shipped, so serving it would
    # hand back released bytes under a URL whose cache-buster already tracks the
    # developer's file (Framework::Version.development_asset_url reads that mtime first) --
    # a framework JS change would then be invisible to the very host meant to be testing it.
    def self.host_dev_file(name)
      return nil unless defined?(Rails) && Rails.respond_to?(:public_path)

      path = Rails.public_path.join("framework-dev", name)
      path if path.exist?
    rescue StandardError
      nil
    end

    DEV_FILES = {
      "plugins.css" => ->(_root) { host_dev_file("plugins.css") || Framework.server_builds.join("plugins.css") },
      "plugins.js" => ->(root) { host_dev_file("plugins.js") || root.join("app/javascript/plugin-render/plugins.js") }
    }.freeze

    # Where /framework-docs/<name> resolves on this host right now, or nil when
    # nothing answers it. The docs helper reads the mtime: these files are served off
    # the engine tree rather than through Propshaft, so the URL carries no digest.
    def self.docs_file_path(name)
      file = DOCS_FILES[name]&.call(Engine.root)
      file if file&.exist?
    end

    def initialize(app, root = nil)
      @app = app
      @root = Pathname(root || Engine.root)
      @file_server = ::Rack::Files.new(@root.join("public").to_s)
    end

    def call(env)
      path = ::Rack::Request.new(env).path_info

      if (response = serve_mapped(env, path, "/framework-docs/", DOCS_FILES))
        return with_cache_control(response, path)
      end

      if (response = serve_mapped(env, path, "/framework-dev/", DEV_FILES))
        return with_cache_control(response, path)
      end

      # Narrow prefixes under /framework/* so the rest of public/framework stays unexposed
      # (the release zip is matched on its own). The docs prefixes carry the generated .md
      # twins of the docs pages; a page URL has no file behind it, so its lookup misses and
      # the request falls through to the docs routes.
      if serves_public_file?(path)
        status, headers, body = serve_with_encoding(env, @file_server)
        return with_cache_control([status, headers, body], path) if status < 400
      end

      @app.call(env)
    end

    private

    # Rack::Files sets Last-Modified and nothing else, so every page view revalidated each
    # multi-MB bundle it links. This middleware sits ahead of ActionDispatch::Static, whose
    # public_file_server.headers never reach these files.
    def with_cache_control(response, path)
      status, headers, body = response
      return response unless status < 400

      headers["cache-control"] ||= cache_control_for(path)
      [status, headers, body]
    end

    def cache_control_for(path)
      return DEV_CACHE_CONTROL if path.start_with?("/framework-dev/")
      return IMMUTABLE_CACHE_CONTROL if path.match?(IMMUTABLE_PATH)

      DEFAULT_CACHE_CONTROL
    end

    # Serves the request through `file_server`, preferring a precompressed sibling the
    # client accepts. A `.br` or `.gz` next to the released file is the same resource in
    # another encoding, so it keeps the plaintext file's Content-Type and only gains
    # Content-Encoding; Rack::Files answers HEAD, Range and If-Modified-Since off whichever
    # file it ends up serving. The sibling is looked up by asking Rack::Files for it rather
    # than by joining paths here, so its own root and traversal checks still decide what
    # exists. Nothing decompresses anywhere: the release wrote those bytes.
    #
    # Vary goes on every response this branch answers, negotiated or not, so a cache can
    # never hand the identity bytes to a client that asked for br, or the reverse.
    def serve_with_encoding(env, file_server)
      path = env["PATH_INFO"]
      accepted = ::Rack::Utils.q_values(env["HTTP_ACCEPT_ENCODING"].to_s)
                              .select { |_encoding, quality| quality.positive? }
                              .map(&:first)

      PRECOMPRESSED_ENCODINGS.each do |encoding, suffix|
        next unless accepted.include?(encoding)

        status, headers, body = file_server.call(env.merge("PATH_INFO" => "#{path}#{suffix}"))
        # No sibling in this encoding, which is the normal case for a version released
        # before 3.2.0. The miss is Rack::Files' own 404 and is dropped, not returned.
        unless status < 400
          body.close if body.respond_to?(:close)
          next
        end

        headers["content-type"] = ::Rack::Mime.mime_type(::File.extname(path), "text/plain")
        headers["content-encoding"] = encoding
        headers["vary"] = "Accept-Encoding"
        return [status, headers, body]
      end

      status, headers, body = file_server.call(env)
      headers["vary"] = "Accept-Encoding" if status < 400
      [status, headers, body]
    end

    def serves_public_file?(path)
      ROOT_PUBLIC_FILES.include?(path.delete_prefix("/")) ||
        PUBLIC_PREFIXES.any? { |prefix| path.start_with?(prefix) } ||
        path.match?(FRAMEWORK_ZIP)
    end

    # The real env goes through with only the two path keys repointed at the resolved
    # file. A forged GET env dropped the request method and every conditional header
    # with it, so HEAD came back with a full body and a revalidating client re-fetched
    # the whole multi-MB bundle on every hit. Rack::Files answers HEAD, OPTIONS,
    # If-Modified-Since and Range itself once it can see them, the same way the
    # public-prefix branch above already lets it. Its status goes back verbatim: this
    # branch resolved a real file, so unlike the public prefixes there is nothing here
    # for the app to answer instead.
    def serve_mapped(env, path, prefix, map)
      return unless path.start_with?(prefix)

      name = path.delete_prefix(prefix).split("?", 2).first
      resolver = map[name]
      return unless resolver

      file = resolver.call(@root)
      return unless file&.exist?

      serve_with_encoding(
        env.merge("PATH_INFO" => "/#{file.basename}", "SCRIPT_NAME" => ""),
        ::Rack::Files.new(file.dirname.to_s)
      )
    end
  end
end
