import { Controller } from "@hotwired/stimulus"

// Connects to data-controller="copy-page"
// Provides a dropdown with: Copy as Markdown, View as Markdown, Copy Markdown link.
export default class extends Controller {
  static targets = ["dropdown", "buttonText"]

  connect() {
    this.closeOnClickOutside = this.closeOnClickOutside.bind(this)
    document.addEventListener("click", this.closeOnClickOutside)
  }

  disconnect() {
    document.removeEventListener("click", this.closeOnClickOutside)
  }

  toggle(event) {
    event.stopPropagation()
    this.dropdownTarget.hidden = !this.dropdownTarget.hidden
  }

  close() {
    this.dropdownTarget.hidden = true
  }

  closeOnClickOutside(event) {
    if (!this.element.contains(event.target)) {
      this.close()
    }
  }

  async copyMarkdown(event) {
    event.preventDefault()
    this.close()

    try {
      const response = await fetch(this.mdUrl())
      // The .md twins are generated by `rake framework:generate_markdown` and are not
      // committed, so a host that has never run it answers 404. fetch resolves on 404,
      // so without this check the error page lands on the clipboard as the "Markdown".
      if (!response.ok) {
        this.showFeedback("Unavailable")
        return
      }
      const text = await response.text()
      await navigator.clipboard.writeText(text)
      this.showFeedback("Copied!")
    } catch (_error) {
      this.showFeedback("Failed")
    }
  }

  viewMarkdown() {
    this.close()
  }

  copyLink(event) {
    event.preventDefault()
    this.close()

    const fullUrl = `${window.location.origin}${this.mdUrl()}`

    navigator.clipboard.writeText(fullUrl).then(() => {
      this.showFeedback("Copied!")
    }).catch(() => {
      this.showFeedback("Failed")
    })
  }

  mdUrl() {
    return `${window.location.pathname}.md`
  }

  showFeedback(message) {
    const original = this.buttonTextTarget.textContent
    this.buttonTextTarget.textContent = message

    setTimeout(() => {
      this.buttonTextTarget.textContent = original
    }, 1500)
  }
}
